# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_NPY=111  CONDA_PY=27
    - CONDA_NPY=112  CONDA_PY=27
    - CONDA_NPY=111  CONDA_PY=35
    - CONDA_NPY=112  CONDA_PY=35
    - CONDA_NPY=111  CONDA_PY=36
    - CONDA_NPY=112  CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "SXHkc2cNSmD8uL/W9DEBhNjkMgrxg51OB6M3awGCy2Wjk/xTAMIqeVwxIipLcv4MLx1Bf+igt4j2I+XRb1ECi0lOF8Sa5rKwTjQ3T1IhptZQKQZsoA2Mg9vn+9/e+NIr6ILm46msbXTKV2giBhcxHqC45V0VWEHEI38tAURctWL8iatczxBwz9XwMEEIyR4SrP6pu6QulgIlMb9YMXqryOV6EaKyOITLLpDOEJuFwnRX7LLashq23kEr+0pyvO8myZIwElrMNbqHEhszE/yI5RYMvtHqr3x958MzNvSo6KFB/yaQc+xI/4rDdgB8NLxLx6ZFSfA9hiqOnnHqlVQ8OHn/SLvORg90XWKPpKHVdhd4/sSPtinimSGakowtc8gZsqLIGDV4IpmTerTMApd3+ryB+IH4nJMjTbynHUhRdhmo9a4tVJJmJEpn/GBkFZv99IlfId/zs4PUkiKAxS9LU1wWfAoacCDYYCxXiT4NraGVpnDzW5CutxNai23/DVRDGrzbuPYPwpNxmeT3Kw0+cG65MZdtd661oaykG41JUZt3E8KX+p3PNDFQe+YKE6H/aKDugcE/uzIhwydUsbg5o8J97uQl+B89bF/jQyV1s1xTK2KR/GRoEgumr5bE//VrJ0Tvnlw632QYM6pzfg+xYIq9iIr7cfbb6MQR/PQZI9s="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
